name: I wanna better salary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f docker/dummy-backend/Dockerfile -t ghcr.io/${{ github.repository }}/dummy-backend:latest docker/dummy-backend/ 
      
      - name: Build Docker image for database
        run: docker build -f docker/dummy-database/Dockerfile -t ghcr.io/${{ github.repository }}/dummy-database:latest docker/dummy-database/
      
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/dummy-backend:latest




























        